version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: report_database
      POSTGRES_USER: leaderbrand
      POSTGRES_PASSWORD: password
    ports:
      - "5342:5432"
    volumes:
      - my_db_data:/var/lib/postgresql/data
volumes:
  my_db_data:

